const shwoproducts = [
  {
    id: 100,
    cover: "./AllproductsImag/headphones/head-1.jpg",
    name: "Headphone",
    price: 500,
    calPrice: 500,
  },
  {
    id: 101,
    cover: "./AllproductsImag/headphones/head-2.jpg",
    name: "Headphone",
    price: 700,
    calPrice: 700,
  },
  {
    id: 102,
    cover: "./AllproductsImag/headphones/head-3.jpg",
    name: "Headphone",
    price: 500,
    calPrice: 500,
  },
  {
    id: 103,
    cover: "./AllproductsImag/headphones/head-4.jpg",
    name: "Headphone",
    price: 550,
    calPrice: 550,
  },
  {
    id: 104,
    cover: "./AllproductsImag/headphones/head-5.jpg",
    name: "Headphone",
    price: 560,
    calPrice: 560,
  },
  {
    id: 105,
    cover: "./AllproductsImag/hoodies/hodie-1.jpg",
    name: "Hoodie",
    price: 200,
    calPrice: 200,
  },
  {
    id: 106,
    cover: "./AllproductsImag/hoodies/hodie-2.jpg",
    name: "Hoodie",
    price: 250,
    calPrice: 250,
  },
  {
    id: 107,
    cover: "./AllproductsImag/hoodies/hodie-3.jpg",
    name: "Hoodie",
    price: 300,
    calPrice: 300,
  },
  {
    id: 108,
    cover: "./AllproductsImag/hoodies/hodie-4.jpg",
    name: "Jacket",
    price: 250,
    calPrice: 250,
  },
  {
    id: 109,
    cover: "./AllproductsImag/hoodies/hodie-5.jpg",
    name: "Jacket",
    price: 300,
    calPrice: 300,
  },
  {
    id: 110,
    cover: "./AllproductsImag/watchs/watch-1.jpg",
    name: "Watch",
    price: 500,
    calPrice: 500,
  },
  {
    id: 111,
    cover: "./AllproductsImag/watchs/watch-2.jpg",
    name: "Watch",
    price: 700,
    calPrice: 700,
  },
  {
    id: 112,
    cover: "./AllproductsImag/watchs/watch-3.jpg",
    name: "Watch",
    price: 800,
    calPrice: 800,
  },
  {
    id: 113,
    cover: "./AllproductsImag/watchs/watch-4.jpg",
    name: "Watch",
    price: 200,
    calPrice: 200,
  },
  {
    id: 114,
    cover: "./AllproductsImag/watchs/main.png",
    name: "Watch",
    price: 1000,
    calPrice: 1000,
  },
  {
    id: 115,
    cover: "./AllproductsImag/bags/bag-1.jpg",
    name: "Bag",
    price: 600,
    calPrice: 600,
  },
  {
    id: 116,
    cover: "./AllproductsImag/bags/bag-2.jpg",
    name: "Bag",
    price: 900,
    calPrice: 900,
  },
  {
    id: 117,
    cover: "./AllproductsImag/bags/bag-3.jpg",
    name: "Bag",
    price: 1100,
    calPrice: 1100,
  },
  {
    id: 118,
    cover: "./AllproductsImag/bags/bag-4.jpg",
    name: "Bag",
    price: 400,
    calPrice: 400,
  },
  {
    id: 119,
    cover: "./AllproductsImag/bags/bag-5.jpg",
    name: "Bag",
    price: 1200,
    calPrice: 1200,
  },
  {
    id: 120,
    cover: "./AllproductsImag/laptops/laptop-1.jpg",
    name: "Dell",
    price: 3000,
    calPrice: 3000,
  },
  {
    id: 121,
    cover: "./AllproductsImag/laptops/laptop-2.jpg",
    name: "Accer",
    price: 2000,
    calPrice: 2000,
  },
  {
    id: 122,
    cover: "./AllproductsImag/laptops/laptop-3.jpg",
    name: "MSI",
    price: 1900,
    calPrice: 1900,
  },
  {
    id: 123,
    cover: "./AllproductsImag/laptops/laptop-4.jpg",
    name: "Apple",
    price: 1500,
    calPrice: 1500,
  },
  {
    id: 124,
    cover: "./AllproductsImag/laptops/laptop-5.jpg",
    name: "Hp",
    price: 2600,
    calPrice: 2600,
  },
  {
    id: 125,
    cover: "./AllproductsImag/phones/phone-1.jpg",
    name: "Iphone",
    price: 2000,
    calPrice: 2000,
  },
  {
    id: 126,
    cover: "./AllproductsImag/phones/phone-2.jpg",
    name: "MI",
    price: 1000,
    calPrice: 1000,
  },
  {
    id: 127,
    cover: "./AllproductsImag/phones/phone-3.jpg",
    name: "Vivo",
    price: 1200,
    calPrice: 1200,
  },
  {
    id: 128,
    cover: "./AllproductsImag/phones/phone-4.jpg",
    name: "Samsung",
    price: 1000,
    calPrice: 1000,
  },
  {
    id: 129,
    cover: "./AllproductsImag/phones/phone-5.jpg",
    name: "Huawei",
    price: 1300,
    calPrice: 1300,
  },
  {
    id: 130,
    cover: "./AllproductsImag/shoes/shoe-1.jpg",
    name: "Shoes",
    price: 700,
    calPrice: 700,
  },
  {
    id: 131,
    cover: "./AllproductsImag/shoes/shoe-2.jpg",
    name: "Shoes",
    price: 800,
    calPrice: 800,
  },
  {
    id: 132,
    cover: "./AllproductsImag/shoes/shoe-3.jpg",
    name: "Shoes",
    price: 600,
    calPrice: 600,
  },
  {
    id: 133,
    cover: "./AllproductsImag/shoes/shoe-4.jpg",
    name: "Shoes",
    price: 800,
    calPrice: 800,
  },
  {
    id: 134,
    cover: "./AllproductsImag/shoes/shoe-5.jpg",
    name: "Shoes",
    price: 300,
    calPrice: 300,
  },
];

export default shwoproducts;
