const Ddata = [
  {
    id: 8,
    cover: "./images/discount/discount-1.png",
    name: "BenuX 2022",
    price: 250,
    calPrice: 250,
  },
  {
    id: 9,
    cover: "./images/discount/discount-2.png",
    name: "Sony TV 1080p",
    price: 450,
    calPrice: 450,
  },
  {
    id: 10,
    cover: "./images/discount/discount-3.png",
    name: "Sony PS4",
    price: 50,
    calPrice: 50,
  },
  {
    id: 11,
    cover: "./images/discount/discount-4.png",
    name: "Setgearr 2022",
    price: 100,
    calPrice: 100,
  },
  {
    id: 12,
    cover: "./images/discount/discount-5.png",
    name: "Tony BGB",
    price: 20,
    calPrice: 20,
  },
  {
    id: 13,
    cover: "./images/discount/discount-6.png",
    name: "RG products",
    price: 200,
    calPrice: 200,
  },
  {
    id: 14,
    cover: "./images/discount/discount-7.png",
    name: "Ranasonic 2022",
    price: 300,
    calPrice: 300,
  },
  {
    id: 15,
    cover: "./images/discount/discount-8.png",
    name: "Pune HD",
    price: 30,
    calPrice: 30,
  },
  {
    id: 16,
    cover: "./images/discount/discount-9.png",
    name: "Sony CCTV",
    price: 80,
    calPrice: 80,
  },
];
export default Ddata;
