const allProductDatas = [
  {
    id: 1,
    discount: 50,
    cover: "./images/flash/flash-1.png",
    name: "Shoes",
    price: 100,
    calPrice: 100,
  },
  {
    id: 2,
    discount: 40,
    cover: "./images/flash/flash-2.png",
    name: "Watch",
    price: 20,
    calPrice: 20,
  },
  {
    id: 3,
    discount: 40,
    cover: "./images/flash/flash-3.png",
    name: "Smart Mobile Black",
    price: 200,
    calPrice: 200,
  },
  {
    id: 4,
    discount: 40,
    cover: "./images/flash/vacuum cleaner.jpg",
    name: "Vacuum cleaner",
    price: 250,
    calPrice: 250,
  },
  {
    id: 5,
    discount: 50,
    cover: "./images/flash/tv.jpg",
    name: "TV",
    price: 100,
    calPrice: 100,
  },
  {
    id: 6,
    discount: 50,
    cover: "./images/flash/fan1.jpg",
    name: "Fun",
    price: 100,
    calPrice: 100,
  },
  {
    id: 7,
    discount: 50,
    cover: "./images/flash/iron.jpg",
    name: "Iron",
    price: 150,
    calPrice: 150,
  },
  {
    id: 8,
    cover: "./images/discount/discount-1.png",
    name: "BenuX 2022",
    price: 250,
    calPrice: 250,
  },
  {
    id: 9,
    cover: "./images/discount/discount-2.png",
    name: "Sony TV 1080p",
    price: 450,
    calPrice: 450,
  },
  {
    id: 10,
    cover: "./images/discount/discount-3.png",
    name: "Sony PS4",
    price: 50,
    calPrice: 50,
  },
  {
    id: 11,
    cover: "./images/discount/discount-4.png",
    name: "Setgearr 2022",
    price: 100,
    calPrice: 100,
  },
  {
    id: 12,
    cover: "./images/discount/discount-5.png",
    name: "Tony BGB",
    price: 20,
    calPrice: 20,
  },
  {
    id: 13,
    cover: "./images/discount/discount-6.png",
    name: "RG products",
    price: 200,
    calPrice: 200,
  },
  {
    id: 14,
    cover: "./images/discount/discount-7.png",
    name: "Ranasonic 2022",
    price: 300,
    calPrice: 300,
  },
  {
    id: 15,
    cover: "./images/discount/discount-8.png",
    name: "Pune HD",
    price: 30,
    calPrice: 30,
  },
  {
    id: 16,
    cover: "./images/discount/discount-9.png",
    name: "Sony CCTV",
    price: 80,
    calPrice: 80,
  },
  {
    id: 17,
    cover: "./images/Special/special-1.png",
    price: 1200,
    calPrice: 1200,
    name: "Electric guitar",
  },
  {
    id: 18,
    cover: "./AllproductsImag/herosection/main-banner.jpg",
    price: 999,
    calPrice: 999,
    name: "banner",
  },
  {
    id: 19,
    cover: "./AllproductsImag/herosection/main-banner-1.jpg",
    price: 999,
    calPrice: 999,
    name: "banner",
  },
  {
    id: 30,
    cover: "./Blogs/mackbook-air.jpg",
    name: "Macbook Air high-end 13-inch",
    category: "computer",
    calPrice: 10000,
    price: 10000,
  },
  {
    id: 31,
    name: "Dell XPS 13 9315",
    cover: "./Blogs/Dell.jpg",
    category: "computer",
    calPrice: 8000,
    price: 8000,
  },
  {
    id: 32,
    cover: "./Blogs/MSI.jpg",
    name: `MSI Titan GT77 HX (2023)`,
    category: "computer",
    calPrice: 12000,
    price: 12000,
  },
  {
    id: 33,
    cover: "./Blogs/iphone.jpg",
    name: "iPhone 14 Pro Max",
    category: "phone",
    calPrice: 3000,
    price: 3000,
  },
  {
    id: 34,
    cover: "./Blogs/samsung.jpg",
    name: "Samsung Galaxy F04",
    category: "phone",
    calPrice: 7000,
    price: 7000,
  },
  {
    id: 100,
    cover: "./AllproductsImag/headphones/head-1.jpg",
    name: "Headphone",
    price: 500,
    calPrice: 500,
  },
  {
    id: 101,
    cover: "./AllproductsImag/headphones/head-2.jpg",
    name: "Headphone",
    price: 700,
    calPrice: 700,
  },
  {
    id: 102,
    cover: "./AllproductsImag/headphones/head-3.jpg",
    name: "Headphone",
    price: 500,
    calPrice: 500,
  },
  {
    id: 103,
    cover: "./AllproductsImag/headphones/head-4.jpg",
    name: "Headphone",
    price: 550,
    calPrice: 550,
  },
  {
    id: 104,
    cover: "./AllproductsImag/headphones/head-5.jpg",
    name: "Headphone",
    price: 560,
    calPrice: 560,
  },
  {
    id: 105,
    cover: "./AllproductsImag/hoodies/hodie-1.jpg",
    name: "Hoodie",
    price: 200,
    calPrice: 200,
  },
  {
    id: 106,
    cover: "./AllproductsImag/hoodies/hodie-2.jpg",
    name: "Hoodie",
    price: 250,
    calPrice: 250,
  },
  {
    id: 107,
    cover: "./AllproductsImag/hoodies/hodie-3.jpg",
    name: "Hoodie",
    price: 300,
    calPrice: 300,
  },
  {
    id: 108,
    cover: "./AllproductsImag/hoodies/hodie-4.jpg",
    name: "Jacket",
    price: 250,
    calPrice: 250,
  },
  {
    id: 109,
    cover: "./AllproductsImag/hoodies/hodie-5.jpg",
    name: "Jacket",
    price: 300,
    calPrice: 300,
  },
  {
    id: 110,
    cover: "./AllproductsImag/watchs/watch-1.jpg",
    name: "Watch",
    price: 500,
    calPrice: 500,
  },
  {
    id: 111,
    cover: "./AllproductsImag/watchs/watch-2.jpg",
    name: "Watch",
    price: 700,
    calPrice: 700,
  },
  {
    id: 112,
    cover: "./AllproductsImag/watchs/watch-3.jpg",
    name: "Watch",
    price: 800,
    calPrice: 800,
  },
  {
    id: 113,
    cover: "./AllproductsImag/watchs/watch-4.jpg",
    name: "Watch",
    price: 200,
    calPrice: 200,
  },
  {
    id: 114,
    cover: "./AllproductsImag/watchs/main.png",
    name: "Watch",
    price: 1000,
    calPrice: 1000,
  },
  {
    id: 115,
    cover: "./AllproductsImag/bags/bag-1.jpg",
    name: "Bag",
    price: 600,
    calPrice: 600,
  },
  {
    id: 116,
    cover: "./AllproductsImag/bags/bag-2.jpg",
    name: "Bag",
    price: 900,
    calPrice: 900,
  },
  {
    id: 117,
    cover: "./AllproductsImag/bags/bag-3.jpg",
    name: "Bag",
    price: 1100,
    calPrice: 1100,
  },
  {
    id: 118,
    cover: "./AllproductsImag/bags/bag-4.jpg",
    name: "Bag",
    price: 400,
    calPrice: 400,
  },
  {
    id: 119,
    cover: "./AllproductsImag/bags/bag-5.jpg",
    name: "Bag",
    price: 1200,
    calPrice: 1200,
  },
  {
    id: 120,
    cover: "./AllproductsImag/laptops/laptop-1.jpg",
    name: "Dell laptop",
    price: 3000,
    calPrice: 3000,
  },
  {
    id: 121,
    cover: "./AllproductsImag/laptops/laptop-2.jpg",
    name: "Accer laptop",
    price: 2000,
    calPrice: 2000,
  },
  {
    id: 122,
    cover: "./AllproductsImag/laptops/laptop-3.jpg",
    name: "MSI laptop",
    price: 1900,
    calPrice: 1900,
  },
  {
    id: 123,
    cover: "./AllproductsImag/laptops/laptop-4.jpg",
    name: "Apple laptop",
    price: 1500,
    calPrice: 1500,
  },
  {
    id: 124,
    cover: "./AllproductsImag/laptops/laptop-5.jpg",
    name: "Hp laptop",
    price: 2600,
    calPrice: 2600,
  },
  {
    id: 125,
    cover: "./AllproductsImag/phones/phone-1.jpg",
    name: "Iphone",
    price: 2000,
    calPrice: 2000,
  },
  {
    id: 126,
    cover: "./AllproductsImag/phones/phone-2.jpg",
    name: "MI phone",
    price: 1000,
    calPrice: 1000,
  },
  {
    id: 127,
    cover: "./AllproductsImag/phones/phone-3.jpg",
    name: "Vivo phone",
    price: 1200,
    calPrice: 1200,
  },
  {
    id: 128,
    cover: "./AllproductsImag/phones/phone-4.jpg",
    name: "Samsung phone",
    price: 1000,
    calPrice: 1000,
  },
  {
    id: 129,
    cover: "./AllproductsImag/phones/phone-5.jpg",
    name: "Huawei phone",
    price: 1300,
    calPrice: 1300,
  },
  {
    id: 130,
    cover: "./AllproductsImag/shoes/shoe-1.jpg",
    name: "Shoes",
    price: 700,
    calPrice: 700,
  },
  {
    id: 131,
    cover: "./AllproductsImag/shoes/shoe-2.jpg",
    name: "Shoes",
    price: 800,
    calPrice: 800,
  },
  {
    id: 132,
    cover: "./AllproductsImag/shoes/shoe-3.jpg",
    name: "Shoes",
    price: 600,
    calPrice: 600,
  },
  {
    id: 133,
    cover: "./AllproductsImag/shoes/shoe-4.jpg",
    name: "Shoes",
    price: 800,
    calPrice: 800,
  },
  {
    id: 134,
    cover: "./AllproductsImag/shoes/shoe-5.jpg",
    name: "Shoes",
    price: 300,
    calPrice: 300,
  },
];

export default allProductDatas;
