const Data = [
  {
    id: 1,
    discount: 50,
    cover: "./images/flash/flash-1.png",
    name: "Shoes",
    price: 100,
    calPrice: 100,
  },
  {
    id: 2,
    discount: 40,
    cover: "./images/flash/flash-2.png",
    name: "Watch",
    price: 20,
    calPrice: 20,
  },
  {
    id: 3,
    discount: 40,
    cover: "./images/flash/flash-3.png",
    name: "Smart Mobile Black",
    price: 200,
    calPrice: 200,
  },
  {
    id: 4,
    discount: 40,
    cover: "./images/flash/vacuum cleaner.jpg",
    name: "Vacuum cleaner",
    price: 250,
    calPrice: 250,
  },
  {
    id: 5,
    discount: 50,
    cover: "./images/flash/tv.jpg",
    name: "TV",
    price: 100,
    calPrice: 100,
  },
  {
    id: 6,
    discount: 50,
    cover: "./images/flash/fan1.jpg",
    name: "Fun",
    price: 100,
    calPrice: 100,
  },
  {
    id: 7,
    discount: 50,
    cover: "./images/flash/iron.jpg",
    name: "Iron",
    price: 150,
    calPrice: 150,
  },
];

export default Data;
